## Setup

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random

In [2]:
# table from https://en.wikipedia.org/wiki/Guess_Who
table = pd.read_csv('simplified_table.csv', sep=';')

In [3]:
table

       Name  Gender   Eyes         Hair Beard Moustache Big nose Glasses  Hat
0      Alex    Male  Brown        Black    No       Yes       No      No   No
1    Alfred    Male   Blue  Light brown    No       Yes       No      No   No
2     Anita  Female   Blue       Blonde    No        No       No      No   No
3      Anne  Female  Brown        Black    No        No      Yes      No   No
4   Bernard    Male  Brown   Dark brown    No        No      Yes      No  Yes
5      Bill    Male  Brown  Light brown   Yes        No       No      No   No
6   Charles    Male  Brown       Blonde    No       Yes       No      No   No
7    Claire  Female  Brown  Light brown    No        No       No     Yes  Yes
8     David    Male  Brown       Blonde   Yes        No       No      No  Yes
9      Eric    Male  Brown       Blonde    No        No       No      No  Yes
10    Frans    Male  Brown  Light brown    No        No       No      No   No
11   George    Male  Brown        White    No        No       No      No  Yes
12   Herman    Male  Brown  Light brown    No        No      Yes      No   No
13      Joe    Male  Brown       Blonde    No        No       No     Yes   No
14    Maria  Female  Brown   Dark brown    No        No       No      No  Yes
15      Max    Male  Brown   Dark brown    No       Yes      Yes      No   No
16     Paul    Male  Brown        White    No        No       No     Yes   No
17    Peter    Male   Blue        White    No        No      Yes      No   No
18   Philip    Male  Brown        Black   Yes        No       No      No   No
19  Richard    Male  Brown   Dark brown   Yes       Yes       No      No   No
20   Robert    Male   Blue   Dark brown    No        No      Yes      No   No
21      Sam    Male  Brown        White    No        No       No     Yes   No
22    Susan  Female  Brown        White    No        No       No      No   No
23      Tom    Male   Blue        Black    No        No       No     Yes   No

In [8]:
RANDOM_PERSON = random.choice(table['Name'].tolist())
person_row = table[table['Name'] == RANDOM_PERSON]
person_row

   Name Gender   Eyes   Hair Beard Moustache Big nose Glasses Hat
21  Sam   Male  Brown  White    No        No       No     Yes  No

# AI GUESSER

_Work in progess_ ⚠️